sm6375-common: manifest: Add missing entries for compatibility_matrix
* Fixes:
ERROR: files are incompatible: The following instances are in the device manifest but not specified in framework compatibility matrix:
    android.hardware.light@2.0::ILight/default
    vendor.samsung.hardware.bluetooth.a2dp@1.0::ISehBluetoothAudioOffload/default
    vendor.samsung.hardware.bluetooth.audio@2.1::ISehBluetoothAudioProvidersFactory/default
    vendor.samsung.hardware.health@2.0::ISehHealth/default
    vendor.samsung.hardware.snap.ISehSnap/default (@1)

Change-Id: I2c85a2d99c51ede28881a78c5c65b18658d17a76